//
// Generated file, do not edit! Created by nedtool 5.2 from Pkt.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PKT_M_H
#define __PKT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>Pkt.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * enum PktType
 * {
 * 
 *     Data = 1;
 *     Ack = 2;
 * }
 * </pre>
 */
enum PktType {
    Data = 1,
    Ack = 2
};

/**
 * Class generated from <tt>Pkt.msg:24</tt> by nedtool.
 * <pre>
 * packet Pkt
 * {
 *     int mid;
 *     int src;
 *     int dest;
 *     int MsgType \@enum(PktType); // Data && Ack
 * }
 * </pre>
 */
class Pkt : public ::omnetpp::cPacket
{
  protected:
    int mid;
    int src;
    int dest;
    int MsgType;

  private:
    void copy(const Pkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Pkt&);

  public:
    Pkt(const char *name=nullptr, short kind=0);
    Pkt(const Pkt& other);
    virtual ~Pkt();
    Pkt& operator=(const Pkt& other);
    virtual Pkt *dup() const override {return new Pkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getMid() const;
    virtual void setMid(int mid);
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
    virtual int getMsgType() const;
    virtual void setMsgType(int MsgType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Pkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Pkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PKT_M_H

